#ifndef HARMONIZE_CONFIG
#define HARMONIZE_CONFIG

namespace config {

#ifdef HARMONIZE_RUNTIME_CORRECTNESS_CHECK
constexpr bool RUNTIME_CORRECTNESS_CHECK = HARMONIZE_RUNTIME_CORRECTNESS_CHECK;
#else
constexpr bool RUNTIME_CORRECTNESS_CHECK = false;
#endif


#ifdef HARMONIZE_REORDER_STRUCT_MEMBERS
constexpr bool REORDER_STRUCT_MEMBERS = HARMONIZE_REORDER_STRUCT_MEMBERS;
#else
constexpr bool REORDER_STRUCT_MEMBERS = true;
#endif

}

#endif // HARMONIZE_CONFIG
