#ifndef HARMONIZE_PREAMBLE
#define HARMONIZE_PREAMBLE

#include<utility>


#define STRINGIFY(x) STRINGIFY_HELPER(x)
#define STRINGIFY_HELPER(x) #x
#define LINE_STRING STRINGIFY(__LINE__)

#ifdef COLOR_ASSERTS
#define ASSERT_TEXT(TEXT) "\n\n\033[33m\033[1m" __FILE__ ":" LINE_STRING " \033[0m\033[33m" TEXT "\033[0m\n"
#else
#define ASSERT_TEXT(TEXT) "\n\n" __FILE__ ":" LINE_STRING TEXT "\n"
#endif


#define ASSERT_HAS_MEMBER_HELPER(TYPE_NAME,MEMBER_NAME,MEMBER_SIGNATURE,EXTRA_TEXT) \
    ::InvokeCheck([](auto x){ return AlwaysTrue< decltype( decltype(x) :: MEMBER_NAME ) >::value;}).template can_invoke<TYPE_NAME>() 

#define ASSERT_HAS_MEMBER(TYPE_NAME,MEMBER_NAME,TYPE_SIGNATURE) ASSERT_HAS_MEMBER_HELPER(TYPE_NAME,MEMBER_NAME,TYPE_SIGNATURE,".")
#define ASSERT_HAS_MEMBER_FOR_TRAIT(TRAIT_NAME, TYPE_NAME,MEMBER_NAME,TYPE_SIGNATURE) ASSERT_HAS_MEMBER_HELPER(TYPE_NAME,MEMBER_NAME,TYPE_SIGNATURE,": The `" #TRAIT_NAME "` trait requires a member named `" #MEMBER_NAME "` with type `" #TYPE_SIGNATURE "`.")

#endif
